apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: env
stringData:

  MYSQL_HOST: &dbhost database
  MYSQL_DATABASE: &dbname laravel
  MYSQL_USER: &dbuser laravel
  MYSQL_PASSWORD: &dbpassword laravel
  MYSQL_RANDOM_ROOT_PASSWORD: '1'
  MYSQL_INITDB_SKIP_TZINFO: 'yes'

  #DB_CONNECTION: sqlite
  #DB_DATABASE: /tmp/database.sqlite
  DB_HOST: *dbhost
  DB_DATABASE: *dbname
  DB_USERNAME: *dbuser
  DB_PASSWORD: *dbpassword

  SESSION_DRIVER: database
  MAIL_MAILER: log
