apiVersion: uitsmijter.io/v1
kind: Tenant
metadata:
  name: php
spec:
  hosts:
    - php.littleletter.de
    - login-nightly.littleletter.de
  interceptor:
    cookie: .littleletter.de
    domain: login-nightly.littleletter.de
    enabled: true
  providers:
    # See https://docs.uitsmijter.io/providers/providers/
    - |
      class UserLoginProvider {
        profile = {};

        constructor(credentials) {
          this.profile = {email: credentials.username, name: "UIT User (" + credentials.username + ")"};
          commit(true);
        }

        get canLogin() {
          return true;
        }

        get userProfile() {
          return this.profile;
        }

        get role() {
          return "user";
        }
      }
