---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: migration-example-php
bases:
  - ../base

resources:
  - namespace.yaml
  - ingress.yaml
  - ingress-login.yaml

patchesStrategicMerge:
  - secrets.yaml
